
server:  
  port: 8090  
  context-path:/auth-mgmt-serivce
  session-timeout: 30  
  tomcat.max-threads: 0  
  tomcat.uri-encoding: UTF-8  
  
spring:  
  datasource:  
    url : jdbc:mysql://localhost:3306/mysql  
    username : root  
    password : Huawei123  
    driverClassName : com.mysql.jdbc.Driver 
  redis:
    host: localhost
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
      
